### ISSUE TITLE
Add close button to modal

### ISSUE THREAD

**Issue by brandonbyr4** [brandonbyr4/openops#55]
I forgot to include a close button with the new InputModal component.  There should be an svg X icon that triggers props.closeModal.

https://heroicons.com/ is where I am getting SVG icons.

**Comment by adrianmarinwork** [comment]
What do you think?

![image](https://user-images.githubusercontent.com/118568289/206927175-654ee773-83d5-4da1-95ef-d87e9aebd391.png)

**Comment by DevAttaKhan** [comment]
I would like to do it.

**Comment by ThePlugJumbo** [comment]
@adrianmarinwork looks perfect.  Might change down the line, but go ahead and submit a pull request for this one.

**Comment by adrianmarinwork** [comment]
Sorry, but what do you mean about "might change down de line"?

**Comment by ThePlugJumbo** [comment]
Nvm, was thinking of the form itself.  Google analytics may just need an API key, PayPal might need a client ID, secret key, etc.
